### PR TITLE
Added Copyright at footer

### LINKED ISSUE #470: Add a  copyright section to the footer.
Implement JavaScript to display the current year automatically, ensuring the copyright information remains up-to-date.

**Ex**: © 2024 Your Company Name. All rights reserved. 

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

@dhairyagothi please kindly assign this issue under gssoc-extd, hacktoberfest-accepted and level1

### PR DESCRIPTION
**Pull request by siri-chandana-macha**
# Pull Request Template for GSoC 2024

## Related Issue

closes: #470

## Description of Changes
The footer automatically displays the current year using JavaScript, ensuring it stays current without manual updates.

## Screenshots / Demo (if applicable)
image

## Checklist for Contributor
- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

**Note:** Make sure to add labels gssoc-extd, hacktoberfest-accepted and level1.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
remove background colour just keep text also add in hamburger menu

**Comment by siri-chandana-macha** [comment]
Ok 👍

**Comment by siri-chandana-macha** [comment]
@dhairyagothi Have a Look! I removed the Background color and also added in hamburger.
Let me Know if any further changes needed.
**Note:**  Make sure to add all the neceassary labels in #470 



image

**Comment by dhairyagothi** [comment]
can you add it herosection.jsx instead of adding in html file ??
if you add it in html file it will be shown on every page 
this is a react project you use react components

**Pull request merged**
