### PR TITLE
Updated settings page added all the details

### PR DESCRIPTION
**Pull request by PraveenUppar**
# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

- closes:#369

## Description of Changes

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

## Type of Pull Request

- [X] Bug Fix
- [X] New Feature
- [X] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
Screenshot 2024-10-21 214444

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
[22:00:50.024] Running build in Washington, D.C., USA (East) – iad1
[22:00:50.162] Cloning github.com/dhairyagothi/StationGuide (Branch: Setting-page-update, Commit: 6fb99bb)
[22:00:52.524] Cloning completed: 2.358s
[22:00:53.440] Restored build cache from previous deployment (7xYzMcxynrfN7oYC57hzcGjAoYNs)
[22:00:53.531] Running "vercel build"
[22:00:54.742] Vercel CLI 37.9.0
[22:00:55.461] Installing dependencies...
[22:00:57.532] 
[22:00:57.532] up to date in 1s
[22:00:57.532] 
[22:00:57.533] 167 packages are looking for funding
[22:00:57.533]   run `npm fund` for details
[22:00:57.550] Running "npm run build"
[22:00:57.720] 
[22:00:57.720] > station-saarthi@0.0.0 build
[22:00:57.720] > vite build
[22:00:57.720] 
[22:00:57.984] [36mvite v5.4.9 [32mbuilding for production...[36m[39m
[22:00:58.081] transforming...
[22:01:01.310] [32m✓[39m 71 modules transformed.
[22:01:01.312] [31mx[39m Build failed in 3.30s
[22:01:01.313] [31merror during build:
[22:01:01.313] [31mCould not resolve "./path_to_back_icon_image" from "src/components/Settings.jsx"[31m
[22:01:01.313] file: [36m/vercel/path0/frontend/src/components/Settings.jsx[31m
[22:01:01.313]     at getRollupError (file:///vercel/path0/frontend/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
[22:01:01.313]     at error (file:///vercel/path0/frontend/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
[22:01:01.313]     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/frontend/node_modules/rollup/dist/es/shared/node-entry.js:20006:24)
[22:01:01.313]     at file:///vercel/path0/frontend/node_modules/rollup/dist/es/shared/node-entry.js:19966:26[39m
[22:01:01.339] Error: Command "npm run build" exited with 1
[22:01:01.583]

**Comment by dhairyagothi** [comment]
Screenshot 2024-10-21 220019


sync fork first there are many commits behind in your branch 
make changes in main branch or update branch @PraveenUppar

**Comment by PraveenUppar** [comment]
I have synced the fork

**Comment by dhairyagothi** [comment]
Could not resolve "./path_to_back_icon_image" from "src/components/Settings.jsx"

Screenshot 2024-10-21 222144

resolve this

**Pull request closed without merging**
