### PR TITLE
Made Navigation component to working 

### PR DESCRIPTION
**Pull request by Raja-Abrar-Khan**
## Description of Changes

Made the component Navigation  into working now you can navigate the trains and see if there are any trains in there , This is my issue only . There is no issue other then my issue there . I will try to make this website even more better in upcoming Prs . In this we search and add the start and destination station and when you search if there exists any train between them then you can see in there. 

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [x] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

## Screenshots / Demo (if applicable)

Screenshot 2024-10-10 005348
Screenshot 2024-10-10 005359
Screenshot 2024-10-10 005359

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by Raja-Abrar-Khan** [comment]
#161 is issue number @dhairyagothi 

Screenshot 2024-10-10 005327
Advanced Tasks: Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as Hard. i build a new feature so this is not level 1 task but bro please assign the issues fast , so that i will make new changes in the website....

**Comment by dhairyagothi** [comment]
Bro sorry but its not train navigation app its platform navigation check figma design please we can't change content ...

**Comment by Raja-Abrar-Khan** [comment]
NO Problem Can make Platform navigaton also assign the issue to me let me make this an issue

**Comment by dhairyagothi** [comment]
> NO Problem Can make Platform navigaton also assign the issue to me let me make this an issue

hehe not that much easy this is main and toughest part of project

**Pull request closed without merging**
