### PR TITLE
added feedback form frontend + backend

### PR DESCRIPTION
**Pull request by AyushSharma72**
issue number #537 

added feedback form 
created a new page in the frontend:
Screenshot (343)

created api in the backend to send email:
Screenshot (344)

created api to save user feedback to database:
image

please add level3 before merge @dhairyagothi

### CODE REVIEW

**Comment by AyushSharma72** [comment]
there is error in deployment i don;t know what it is 😭 @dhairyagothi

**Comment by dhairyagothi** [comment]
image

@AyushSharma72 please fix this

**Comment by AyushSharma72** [comment]
> image
> 
> @AyushSharma72 please fix this

Ok fixed @dhairyagothi

**Comment by dhairyagothi** [comment]
GREAT @AyushSharma72

**Pull request merged**
