### PR TITLE
Update schedule.jsx

### PR DESCRIPTION
**Pull request by pragyanbhatt1213**
# Pull Request: Implement NotificationPage Component

## Description of Changes
This PR implements a new NotificationPage component for the project. The component displays a list of notifications with icons, messages, and timing information.

Key features implemented:
- Responsive layout for notifications
- Mapping through an array of notification objects
- Basic styling for each notification item

## Type of Pull Request
- [X] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] UI/UX Enhancement
- [ ] Other (Specify): _______________

## Screenshots / Demo
image

## Checklist for Contributor
- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the NotificationPage component thoroughly.
- [X] My PR addresses only the NotificationPage component implementation.
- [X] I have added necessary comments to my code for clarity.
- [X] I have checked that my changes do not introduce any breaking changes.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's React coding standards and best practices.
- [X] I have tested the component on different screen sizes for responsiveness.

## Additional Information
The NotificationPage component is currently using mock data. In future iterations, it can be connected to a real data source or API.

## Questions for Reviewers
- Is the current structure of the NotificationPage component appropriate for the project's needs?
- Are there any additional features you'd like to see implemented in this component?
- Do you have any suggestions for improving the styling or layout of the notifications?

I'm open to any feedback and suggestions to improve this component. Thank you for reviewing my contribution!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
issue no @pragyanbhatt1213 ??

**Comment by pragyanbhatt1213** [comment]
> issue no @pragyanbhatt1213 ??
> 
Issue no. 245

**Comment by dhairyagothi** [comment]
> > issue no @pragyanbhatt1213 ??
> 
> Issue no. 245

it is PR no.

**Comment by pragyanbhatt1213** [comment]
> > > issue no @pragyanbhatt1213 ??
> > 
> > Issue no. I don't know 😅
> 
> it is PR no.
Where can I find it?

**Comment by dhairyagothi** [comment]
> > > > issue no @pragyanbhatt1213 ??
> > > 
> > > 
> > > Issue no. I don't know 😅
> > 
> > 
> > it is PR no.
> > Where can I find it?

check in issue section

**Comment by pragyanbhatt1213** [comment]
> > > > > issue no @pragyanbhatt1213 ??
> > > > 
> > > > 
> > > > Issue no. I don't know 😅
> > > 
> > > 
> > > it is PR no.
> > > Where can I find it?
> 
> check in issue section 

Issue no. 259

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
