### PR TITLE
layout

### PR DESCRIPTION
**Pull request by Veda273**
# Pull Request Template for GSoC 2024

#440 

closes:
I did the following changes:
1)added a show options/hide options toggle to maintain neat and spacious layout.
2)styled the headings using animation keyframes and altered the styling using text shadow.
3)added back to top feature

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

## Type of Pull Request

- [ ] Bug Fix
- [ ] New Feature
- [X ] Performance Improvement
- [ ] Documentation Update
- [X ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

https://github.com/user-attachments/assets/5a835139-60ac-4ada-80c1-bcfe77ad0361

## Checklist for Contributor
use'X' in [ ] to check it .

- [X ] I have reviewed my code before submission.
- [X ] I have read and followed the project's Contribution Guidelines.
- [X ] I have tested the code thoroughly.
- [X ] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ ] I have added comments to my code where necessary for clarity.
- [ X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X ] My PR addresses only one issue; I have created separate PRs for other issues.
- [ X] I have ensured that the PR does not include unrelated files.
- [X ] I am mindful of the project's coding standards and best practices.

@dhairyagothi , please review my pr.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
yrrrr don't change UI . keep it same as figma design

**Comment by Veda273** [comment]
okay..i will change it.

**Comment by Veda273** [comment]
https://github.com/user-attachments/assets/e1d5fed8-60f2-4f75-9038-c07b9eade5fb

I made the following changes without changing the figma design:
1)Sticky Navbar: The navbar is now sticky, staying at the top as you scroll.
2)Subtle Hover and Shadow Effects: Improved hover effects and shadows on action buttons for better visual hierarchy.
3)animation to heading for better visual appearance.
@dhairyagothi please review my pr.

**Comment by dhairyagothi** [comment]
navbar is not good @Veda273 
other then that i don't see any changes

**Comment by Veda273** [comment]
@dhairyagothi I'll make the final changes and update you by tomorrow

**Comment by Veda273** [comment]
image
@dhairyagothi is it ok now?

**Comment by dhairyagothi** [comment]
Keep it as Figma UI no background in navbar and also components of navbar are not ok . Previous one is good no changes needed

**Comment by Veda273** [comment]
so, is the issue closed?

**Comment by dhairyagothi** [comment]
you have added fade in fade out animation that is good just add that make a new PR

**Comment by Veda273** [comment]
okk..done

**Comment by Veda273** [comment]
@dhairyagothi , please review

**Comment by dhairyagothi** [comment]
> @dhairyagothi , please review

I will check it till night

**Comment by Veda273** [comment]
@dhairyagothi since i did not make much changes, i request you to close this issue by assigning level 1..

**Comment by dhairyagothi** [comment]
changes will mashup repo and there are conflicts bro

**Pull request closed without merging**
