### PR TITLE
issue51

### PR DESCRIPTION
**Pull request by ash-k121**
# Pull Request Template for GSoC 2024

## Related Issue
issue no 51

## Type of Pull Request

- [ ] New Feature

(Please check relevant boxes by entering an "X" inside them)

image

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [ X] I have reviewed my code before submission.
- [ X] I have read and followed the project's Contribution Guidelines.
- [ X] I have tested the code thoroughly.
- [X ] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ X] I have added comments to my code where necessary for clarity.
- [X ] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X ] My PR addresses only one issue; I have created separate PRs for other issues.
- [ X] I have ensured that the PR does not include unrelated files.
- [ X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@ash-k121 there are merge conflicts and we don't want train booking check figma UI we want like that

**Comment by ash-k121** [comment]
> @ash-k121 there are merge conflicts and we don't want train booking check figma UI we want like that

okay

**Comment by dhairyagothi** [comment]
bro there are multiple conflicts ,....

and please share ss

**Comment by ash-k121** [comment]
> bro there are multiple conflicts ,....
> 
> and please share ss

You can ignore the conflicts in backend package folders (as i was trying to create the user and ticket schema), i have just added a file for ticket schema (backend)and booking page (frontend) and regarding the figma ui i’ll update it asap

**Comment by dhairyagothi** [comment]
> > bro there are multiple conflicts ,....
> > and please share ss
> 
> You can ignore the conflicts in backend package folders (as i was trying to create the user and ticket schema), i have just added a file for ticket schema (backend)and booking page (frontend) and regarding the figma ui i’ll update it asap

bro without seeing your work and with conflicts PR how can i merge

**Comment by ash-k121** [comment]
> > > bro there are multiple conflicts ,....
> > > and please share ss
> > 
> > 
> > You can ignore the conflicts in backend package folders (as i was trying to create the user and ticket schema), i have just added a file for ticket schema (backend)and booking page (frontend) and regarding the figma ui i’ll update it asap
> 
> bro without seeing your work and with conflicts PR how can i merge

i am not asking you to merge ,i’ll solve the conflicts

**Comment by dhairyagothi** [comment]
> > > > bro there are multiple conflicts ,....
> > > > and please share ss
> > > 
> > > 
> > > You can ignore the conflicts in backend package folders (as i was trying to create the user and ticket schema), i have just added a file for ticket schema (backend)and booking page (frontend) and regarding the figma ui i’ll update it asap
> > 
> > 
> > bro without seeing your work and with conflicts PR how can i merge
> 
> i am not asking you to merge ,i’ll solve the conflicts

ya bro you solve it but share me some video of your changes

**Comment by ash-k121** [comment]
sure

> > > > > bro there are multiple conflicts ,....
> > > > > and please share ss
> > > > 
> > > > 
> > > > You can ignore the conflicts in backend package folders (as i was trying to create the user and ticket schema), i have just added a file for ticket schema (backend)and booking page (frontend) and regarding the figma ui i’ll update it asap
> > > 
> > > 
> > > bro without seeing your work and with conflicts PR how can i merge
> > 
> > 
> > i am not asking you to merge ,i’ll solve the conflicts
> 
> ya bro you solve it but share me some video of your changes

sure

**Pull request closed without merging**
