### PR TITLE
Updated the hamburger menu size and content to improve visibility and user experience.

### PR DESCRIPTION
**Pull request by PraveenUppar**
# Pull Request Template for GSoC 2024

## Related Issue
- Updated the hamburger menu size and content to improve visibility and user experience.
- closes:#72

## Description of Changes
- Corrected issues where the menu content was not displaying properly, ensuring that all options are now visible.
- Hamburger Menu Size Adjustment

## Type of Pull Request

- [X] Bug Fix
- [ ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [X] Other (Specify): UI/UX

## Screenshots / Demo (if applicable)
Screenshot 2024-10-06 002429

## Checklist for Contributor

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

N/A

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@PraveenUppar increase width of hamburger previous one is good . No need of this changes . 

If you can make any changes make it . 

Don't use `px` instead of `vw` . It removes responsiveness

**Comment by PraveenUppar** [comment]
The problem with the previous hamburger was that it was taking up more space on the homepage which was not a good user experience if you don't like the changes made in the hamburger sizing I will resubmit the PR with hamburger font size and visibility changes only

**Comment by dhairyagothi** [comment]
> The problem with the previous hamburger was that it was taking up more space on the homepage which was not a good user experience if you don't like the changes made in the hamburger sizing I will resubmit the PR with hamburger font size and visibility changes only 

I think previous one is good . Let it be . I am doing some changes you check it once then make a PR

**Comment by PraveenUppar** [comment]
ok thank you for your feedback

**Comment by PraveenUppar** [comment]
ok thank you for your feedback

**Pull request closed without merging**
