### PR TITLE
Fixes #10 Fixing white Background of Home section

### LINKED ISSUE #10: Fixing white Background of Home section
# ✨ Feature Request

white background image of hero section 
### **Description of the Feature**

white background image of hero section 

### **Problem Statement**

image

fixing this

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by rishyym0927**
# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]
issue #10 
closes:

## Description of Changes

white background image of hero section

## Type of Pull Request

- [x] Bug Fix
- [x] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
image

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
don't remove it keep it as UI check [CONTRIBUTION.md](https://github.com/dhairyagothi/StationGuide/blob/main/CONTRIBUTING.md) and make it as [Figma UI ](https://github.com/dhairyagothi/StationGuide/blob/main/StationGuideFigma.md)

**Comment by dhairyagothi** [comment]
don't remove it keep it as UI check [CONTRIBUTION.md](https://github.com/dhairyagothi/StationGuide/blob/main/CONTRIBUTING.md) and make it as [Figma UI ](https://github.com/dhairyagothi/StationGuide/blob/main/StationGuideFigma.md)

**Comment by rishyym0927** [comment]
Can you please elaborate the issue to me again? I guess it was about to remove the white background, the image contained background , how can I solve it then?

**Comment by dhairyagothi** [comment]
> Can you please elaborate the issue to me again? I guess it was about to remove the white background, the image contained background , how can I solve it then?

have you checked figma design ?? we want that whitish bg in bottom

**Pull request closed without merging**
