### PR TITLE
Added stations, enhance the search bar, added loading animation at station page, added zone and address of the stations.

### PR DESCRIPTION
**Pull request by Vaibhav-Samdani**
# Pull Request Template for GSoC 2024

## Related Issue

#196 

## Description of Changes

- [X] Added the station list available in india.
- [X] Data coming from backend using api.
- [x] Improved search feature.
- [x] Added loading animation on station page.
- [x] Added dataset of the station along with their address, zone and code for further feature.
🥇 Plesase assign level3 as the work i have done!.

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [x] Code Refactoring
- [ ] Security Enhancement
- [x] Other (Specify): Added station list.

## Screenshots / Demo
image

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Vaibhav-Samdani please share a video of changes

**Comment by Vaibhav-Samdani** [comment]
@dhairyagothi as the size of video is greater than the limit of the github, I have uploaded on drive. Here is the link : 

https://drive.google.com/file/d/1YlLYsvOkeIh1SPQR9mwHLAvG6cGCl5hq/view?usp=sharing

**Comment by dhairyagothi** [comment]
@Vaibhav-Samdani access

**Comment by Vaibhav-Samdani** [comment]
@dhairyagothi access granted!

**Comment by dhairyagothi** [comment]
that's really great @Vaibhav-Samdani 
can you please add api files in frontend folder ??? so that it can be access in deployment

**Comment by Vaibhav-Samdani** [comment]
Can you explain me what do you mean by api files in frontend?

**Comment by dhairyagothi** [comment]
image

@Vaibhav-Samdani see this while deploying frontend on vercel it is not showing station because data is fetch from backend and backend is unable to deploy

**Comment by dhairyagothi** [comment]
can we fix this @Vaibhav-Samdani

**Comment by Vaibhav-Samdani** [comment]
@dhairyagothi added the stations to frontend so that it will run without backend. check it now!

**Comment by dhairyagothi** [comment]
thank you so much @Vaibhav-Samdani loved the preloader

**Pull request merged**
