### PR TITLE
Added "Already have an account then login" link to Signup page and vice versa

### PR DESCRIPTION
**Pull request by ShivaniNikam1**
## Description of Change
I have added links of "Already have an account then Login" to register page and vice versa.

For Login page, below is the image of before and after page

Before:
login_prev

After:
login_after

Similarly for Register page, below is the image of before and after page

Before:
register-prev

After:
register_after

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

## Type of Pull Request
Enhancement

I would really appreciate it if you could take a look at this PR and provide your feedback.

Thank you for your time!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
Hey @ShivaniNikam1 nice to see you here 

But please follow steps 
- first create a issue
- after getting issue assigned
- work on issue 
- make a PR 


for now create a issue 
and please dont change UI colours

**Comment by dhairyagothi** [comment]
image

change this colour to green 
and please create an issue

**Comment by dhairyagothi** [comment]
@ShivaniNikam1 any updates ??

**Comment by ShivaniNikam1** [comment]
yesss, got it. Will make the necessary changes right now!

**Comment by dhairyagothi** [comment]
perfect @ShivaniNikam1 good to go now

**Review by dhairyagothi — APPROVED** [review]
Good @ShivaniNikam1

**Comment by dhairyagothi** [comment]
closes: #21

**Pull request merged**
