### PR TITLE
Add more Buttons  in the Landing Page and add a new station . In Next Pr i will make navigate for every button by making some new routes

### PR DESCRIPTION
**Pull request by Raja-Abrar-Khan**
# Pull Request Template for GSoC 2024

## Related Issue

This PR Add new station in the station page and It make buttons in the landing page . For now it will navigate to the same place but in next Pr i will make the new Routes and make navigate for every button.

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [x] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
Screenshot 2024-10-08 010635
Screenshot 2024-10-08 010650
Screenshot 2024-10-08 010701

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [ ] My PR addresses only one issue; I have created separate PRs for other issues.
- [x} I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  merge My pr in the next pr i will make new routes for every button related component

**Comment by irekponor** [comment]
@Raja-Abrar-Khan assign them to me, let me assist you in making the new routes

**Comment by dhairyagothi** [comment]
@Raja-Abrar-Khan can you add routes in images instead of creating a button for them ?

**Comment by dhairyagothi** [comment]
I will check PR and merge currently not using laptop @Raja-Abrar-Khan

**Comment by Raja-Abrar-Khan** [comment]
sure i can  add routes in images instead of buttons or in both if thats what you want , that will be my next task .But merge this One first then i can work my way up

**Comment by dhairyagothi** [comment]
i will assign level accordingly here is juat 10 line of code change i will assign only 10 points

**Review by dhairyagothi — APPROVED** [review]

**Comment by dhairyagothi** [comment]
what is issue no ?? @Raja-Abrar-Khan

**Pull request merged**
