### PR TITLE
Add favorites Stations

### LINKED ISSUE #250: Add favourite Station
# ✨ Feature Request

### **Description of the Feature**
Clicking on the star mark on the station card should add it to a new list of stations containing the favourites for the user.

### **Proposed Solution**
On clicking the star should send data of the station to the backend to associate with the user profile.
Screenshot 2024-10-14 202138

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Pull Request Template for GSoC 2024

## Related Issue
 fixes #250 
This PR allows user to add their favorite stations on the stations page.

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

https://github.com/user-attachments/assets/fdf9ce55-a65f-46cb-8a10-1493d4221f3a

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
add favourite in last

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi updated favorites at last

**Comment by haseebzaki-07** [comment]
@dhairyagothi please add some level to the PR

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi labels???

**Comment by haseebzaki-07** [comment]
hey @dhairyagothi levels please!!

**Comment by dhairyagothi** [comment]
Sorry @haseebzaki-07 i forgot it

**Comment by dhairyagothi** [comment]
Please check if any other pr is also there remaining to add label @haseebzaki-07

**Comment by haseebzaki-07** [comment]
No @dhairyagothi All PRs are with labels. Please let me know if there are good issues that I can work.

**Pull request merged**
