### PR TITLE
added loader to all possible pages

### PR DESCRIPTION
**Pull request by AyushSharma72**
issue number #518 

added loader to all possible forms
screen short:
Screenshot (293)

ss2:
Screenshot (294)

ss3:
Screenshot (295)

please review this pr @dhairyagothi

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]

**Comment by dhairyagothi** [comment]
there are issues with deployment 😭😭

**Comment by AyushSharma72** [comment]
> there are issues with deployment 😭😭

you didn't replied me only you can see the issue in the deployment i cannot see i was waiting for you to tell me the issue can you tell me the issue i will try to resolve it  @dhairyagothi

**Comment by dhairyagothi** [comment]
> > there are issues with deployment 😭😭
> 
> you didn't replied me only you can see the issue in the deployment i cannot see i was waiting for you to tell me the issue can you tell me the issue i will try to resolve it @dhairyagothi

no problem bro i will resolve just few lines change , its issue with vercel deployment

**Comment by AyushSharma72** [comment]
> > > there are issues with deployment 😭😭
> > 
> > 
> > you didn't replied me only you can see the issue in the deployment i cannot see i was waiting for you to tell me the issue can you tell me the issue i will try to resolve it @dhairyagothi
> 
> no problem bro i will resolve just few lines change , its issue with vercel deployment

ok thanks @dhairyagothi

**Pull request merged**
