### PR TITLE
Readme Updation

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Pull Request Template for GSSoC 2024 Extended

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes: Issue #112 

## Description of Changes

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

1) Added:  Animated line separators
Add animated line separators in between sections and also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution

2) Modified: The Contributors section.
Made the Contributors section look more attractive.

3) Modified:  The Contact Information by replacing it with a Team section
The Team section will look more organized and readable.

## Type of Pull Request

- [ ] Bug Fix
- [ ] New Feature
- [ ] Performance Improvement
- [X] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

https://github.com/user-attachments/assets/1dab6259-d6d2-477d-85ba-271e76fb4530

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
Please assign this PR to me and also assign the correct labels:
- level1
- gssoc-ext
- hacktoberfest-accepted
image
Thanks for reviewing the PR.

**Comment by dhairyagothi** [comment]
@rajdeepchakraborty-rc will contrib.rock update contributors automatically ?

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc will contrib.rock update contributors automatically ?

Remember the link I had provided for your repository's contributors? I have made the contributor section responsive using the feed from your repository's Contributors feed. The README will update along with the Repository's updates on Contributors.

**Comment by rajdeepchakraborty-rc** [comment]
@dhairyagothi Please review the PR. Just wanted to remind you about it.

**Comment by rajdeepchakraborty-rc** [comment]
@dhairyagothi Thanks for the review! Also wanted to ask whether you will be closing the issue #112 or should I close it?

**Pull request merged**
