### PR TITLE
Added station services

### LINKED ISSUE #203: Implement Station services
# ✨ Feature Request

### **Description of the Feature**
I want to implement the station services backend and frontend

Screenshot 2024-10-12 000127

### **Problem Statement**
A user entering station and date should see the available coolies , wheelchairs and cloakroom and can book the services accordingly and gets a notification for the booking.

### **Proposed Solution**
I will add backend controllers for fetching coolies , cloakroom and wheelchairs for specific stations and then integrate with the frontend to be able to book by a user.

### **Are you participating in GSSoC?**
- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #203

## Description of Changes

This PR encourages the booking functionality of services at a specific station by fetching all the available services with count. 
It has suggestions for stations in the database from which one  can select the desired station to proceed with the booking.

It has backend routes and controllers for fetching all stations , creating a station, fetching stations bookings,  fetching coolies , wheelchairs and cloakroom for a station by Id.

Also i migrated the bookings component from pages/booking.jsx to components/BookingForm.jsx and updated the routes for improving modularity of the code.

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

https://github.com/user-attachments/assets/ebf5930f-0171-4383-ad42-12997c599bfe

## Screenshots / Demo (if applicable)
(https://github.com/user-attachments/assets/896372ca-424d-454e-9b59-2b2408cfa31c)

get all stations: 
Screenshot 2024-10-13 013019

get all stations booking by id:
Screenshot 2024-10-13 013058

get station coolie booking:
Screenshot 2024-10-13 013238

get station wheelchair booking:
Screenshot 2024-10-13 013303

## Checklist for Contributor
use'X' in [X] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@haseebzaki-07 good but add booking.jsx in pages folder only don't add it in component 
also share video of working of backend i am unable to see in hosting

**Comment by haseebzaki-07** [comment]
@dhairyagothi sure I will add the bookings back in pages and please explain me what you want to see in the backend as these are all the changes I have made.

**Comment by haseebzaki-07** [comment]
@dhairyagothi You wont be able to see the backend functioning without a database. 
Also I had added the booking page back to pages.

**Comment by dhairyagothi** [comment]
@haseebzaki-07  i know that but there is problem in deployment in backend on vercel 

i kust want to check how changes is working with backend

**Review by dhairyagothi — APPROVED** [review]

**Comment by dhairyagothi** [comment]
great work @haseebzaki-07 kudos to you thankyou so much

**Comment by haseebzaki-07** [comment]
@dhairyagothi it's my pleasure

**Pull request merged**
