### PR TITLE
Integrated backend with frontend login and register functionality

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request Template for GSoC 2024

## Related Issue

Integrating the login/signup api with frontend. #34

closes:

## Description of Changes

So in this pull request i have done the login/register functionality on frontend using the logic build on backend though this users can now properly login and signup through their accounts. I have also added the verification token so that users don't have to login again and again and they are automatically logged in right. Also it stores the token as a cookie so proper integration is done. Now user can create new account or login to existing accounts seamlessly.

## Type of Pull Request

- [ ] Bug Fix
- [X ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

image
image

## Checklist for Contributor
use'X' in [ ] to check it .

- [ X] I have reviewed my code before submission.
- [ X] I have read and followed the project's Contribution Guidelines.
- [ X] I have tested the code thoroughly.
- [ X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ X] I have added comments to my code where necessary for clarity.
- [ X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [ X] My PR addresses only one issue; I have created separate PRs for other issues.
- [ X] I have ensured that the PR does not include unrelated files.
- [ X] I am mindful of the project's coding standards and best practices.

@dhairyagothi Check the pull request and add required labels and merge it.

### CODE REVIEW

**Review by dhairyagothi — COMMENTED** [review]
image

please resolve conflicts @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@dhairyagothi Done I think you pushed someone else code first before mine that's why it happened check once again now.

**Comment by tarunkumar2005** [comment]
Wait i have one more thing to change just a min

**Comment by tarunkumar2005** [comment]
@dhairyagothi Done I think you pushed someone else code first before mine that's why it happened check once again now.

**Comment by dhairyagothi** [comment]
@tarunkumar2005 please share a video of changes in your local

**Comment by tarunkumar2005** [comment]
@dhairyagothi I have shared it on linkedin dm here it is not accepting larger than 10Mb if you have some issue then you can tell me directly on linkedin. any more issues in this that needs to be fixed.

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
