### PR TITLE
 Chatbot Integration for Station Saarthi !!

### LINKED ISSUE #279: Improving the Chatbot !!
# 🖥️ Frontend Issue

### **Description**
The chatbot on our platform is not responsive to user questions. It consistently returns the same message: "Sorry, I am not having the answer for that" for all queries, even when valid inputs are provided.

Navigate to the chatbot on the website/app.
Enter a valid query or question.
The chatbot returns the message: "Sorry, I am not having the answer for that."

### **Expected behavior**
The chatbot should provide appropriate responses to user queries based on its knowledge base or predefined answers.

### **Actual behavior**
Regardless of the question asked, the chatbot returns a single response: "Sorry, I am not having the answer for that."

### **Screenshots or Video**
image

### Are you participating in GSSoC?
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes: #279

### Objective: 
- Implemented a chatbot on the Station Saarthi website to assist users in accessing real-time train information and station 
  details efficiently.

### Features Added:

 - Train Schedule Assistance: Users can inquire about train timings, routes, and stations through the chatbot. 
-  Station Information: Provides key details about various train stations, including facilities, nearby attractions, and services 
     available.
-  Real-Time Updates: Integrated APIs to deliver real-time updates about train delays, cancellations, or platform changes (if applicable).
-  FAQs: Automated responses to common questions like ticket availability, station amenities, and train classes.
- User Interaction Flow: Simplified conversational interface to guide users based on their queries (e.g., “Enter your departure station”).

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [x] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

image
image
image

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by SrijaVuppala295** [comment]
@dhairyagothi ,   I have created a new chatbot , with works functionally , and answers any queries related to trains , PLEASE INCREASE MY LEVEL OF THE PR , as it  took a lot of time to complete !!!

**Comment by dhairyagothi** [comment]
there is some deployment error @SrijaVuppala295

**Comment by dhairyagothi** [comment]
image

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , now its resolved , please check it

**Comment by dhairyagothi** [comment]
still same  path is not correct
image

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , I have made changes

**Comment by dhairyagothi** [comment]
same problem bro wait i will check it soon

**Comment by SrijaVuppala295** [comment]
> same problem bro wait i will check it soon

Okay bro

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , i have resolved the conflicts

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , Sir if the deployment error again occurs, should i create an another PR

**Comment by dhairyagothi** [comment]
> @dhairyagothi , Sir if the deployment error again occurs, should i create an another PR

yes please

**Comment by dhairyagothi** [comment]
its react project html js will not work still add js in html file only don't create seperate file

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , Sure !!!

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , I have created a new PR , please review it , it doesnt have any issues , #417

**Pull request closed without merging**
