### PR TITLE
Added About Us page

### LINKED ISSUE #124: Addition of a contact page and about us page
There is no contact and about us page. The website will look complete once we add them. I believe as a UI/UX designer and web developer, I can create an attractive about us and contact page for you. Could you please assign me this task?

### PR DESCRIPTION
**Pull request by meghanakn473**
# Pull Request Template for GSoC 2024

closes: #124

## Description of Changes
 
Adding about us page gives user idea about vision, mission and unique features of their app and their motives.

## Type of Pull Request

- [ ] Bug Fix
- [X ] New Feature
- [X ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

https://github.com/user-attachments/assets/f83226ed-de4b-4775-b8a9-a6bb6cd84ac3

## Checklist for Contributor

- [ X] I have reviewed my code before submission.
- [X ] I have read and followed the project's Contribution Guidelines.
- [X ] I have tested the code thoroughly.
- [X ] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X ] I have added comments to my code where necessary for clarity.
- [X ] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X ] My PR addresses only one issue; I have created separate PRs for other issues.
- [X ] I have ensured that the PR does not include unrelated files.
- [ X] I am mindful of the project's coding standards and best practices.

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### CODE REVIEW

**Comment by meghanakn473** [comment]
@dhairyagothi please review and merge and do assign level 2, gssoc-extd, hacktoberfest-accepted labels
thank you

**Comment by meghanakn473** [comment]
@dhairyagothi ??

**Comment by dhairyagothi** [comment]
please don't change FIGMA UI check all readme files first dont want navbar 

make according to FIGMA design

**Comment by dhairyagothi** [comment]
image


don't want this navbar 
and its react project edit in `about.jsx` file not in `index.html`

**Comment by dhairyagothi** [comment]
thankyou for your contribution and time @meghanakn473 but proceed forward with changes if you know REACT.JS

**Comment by meghanakn473** [comment]
I'll update it

**Pull request closed without merging**
