### PR TITLE
removed all unused dependencies issue #150

### PR DESCRIPTION
**Pull request by AyushSharma72**
i removed all the unused dependencies thereby decreasing the size of nodemodules

image

please add gssoc-ext and level1 label before merge @dhairyagothi

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@AyushSharma72 conflicts dont make multiple PR without sync fork this leads to conflicts

**Comment by AyushSharma72** [comment]
> @AyushSharma72 conflicts dont make multiple PR without sync fork this leads to conflicts

@dhairyagothi

**Comment by dhairyagothi** [comment]
> > @AyushSharma72 conflicts dont make multiple PR without sync fork this leads to conflicts
> 
> @dhairyagothi

???
image

**Comment by AyushSharma72** [comment]
> > > @AyushSharma72 conflicts dont make multiple PR without sync fork this leads to conflicts
> > 
> > 
> > @dhairyagothi
> 
> ??? image

done @dhairyagothi

**Comment by dhairyagothi** [comment]
image

@AyushSharma72

**Comment by AyushSharma72** [comment]
> image
> 
> @AyushSharma72

I will close ths and make another pr for this

**Pull request closed without merging**
