### PR TITLE
Added a Custom Cursor Effect

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
# Pull Request 

## Description of Changes
-> Used Recursive pattern of Circles for attractive cursor design .
-> It makes website more attractive and User-Interactive.

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [X] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

## Screenshots / Demo 

https://github.com/user-attachments/assets/756626f2-87c4-4f7a-8168-6567f5fc5306

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
good @AnujShrivastava01

**Review by dhairyagothi — APPROVED** [review]

**Comment by AnujShrivastava01** [comment]
> good @AnujShrivastava01

Thankyou ! 
Now please assign me labels in pull request also for points evaluation and then merge the pull request .

**Comment by AnujShrivastava01** [comment]
Please check the level bagde I was assigned level2 for the issue .
Please change it .
# Label Screenshot
image

**Comment by dhairyagothi** [comment]
> Please check the level bagde I was assigned level2 for the issue . Please change it .
> 
> # Label Screenshot
> image

bro its just normal change added cursor .
although i will assign you level 2 later on it will be assigned as level 1 if they found.....

**Comment by AnujShrivastava01** [comment]
Ok Bro, Thankyou for your  support and quick reply.

**Comment by dhairyagothi** [comment]
> Ok Bro, Thankyou for your support and quick reply.

sure bro tell me your tech stacks speciality, so i will tell you issues if you want

**Comment by AnujShrivastava01** [comment]
> > Ok Bro, Thankyou for your support and quick reply.
> 
> sure bro tell me your tech stacks speciality, so i will tell you issues if you want

Yes Bro sure , I have just started my Open Source journey and learning day by day.
Currently I have my skills in Enhancing Frontend Using HTML , CSS and JS.
Its great to contribute in your project and work with you.
I have also connected with you on Linkedin .

**Pull request merged**
