### PR TITLE
Added cloakroom and wheelchair booking backend routes

### LINKED ISSUE #103: [Backend Issue]: Adding backend for booking
# 🛠️ Backend Issue

### **Description**
The application does not have booking functionality . A backend route/api is needed for the purpose

### **Steps to Reproduce**
I will add bookingController/api in the backend of the project.
   
### **Are you participating in GSSoC?**
- [x ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Pull Request Template for GSoC 2024

## Related Issue

fixes #103 

## Description of Changes

I have created models and controllers for WheelChair booking and Cloakroom booking. 

## Type of Pull Request

- [ ] Bug Fix
- [X ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

Screenshot 2024-10-07 152323

Screenshot 2024-10-07 153153

## Checklist for Contributor
use 'X' in [ ] to check it .

- [X ] I have reviewed my code before submission.
- [X ] I have read and followed the project's Contribution Guidelines.
- [X ] I have tested the code thoroughly.
- [X ] I have attached related issue numbers, screenshots, or videos (if applicable).
-  [X] I have added comments to my code where necessary for clarity.
- [X ] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X ] My PR addresses only one issue; I have created separate PRs for other issues.
- [X ] I have ensured that the PR does not include unrelated files.
- [X ] I am mindful of the project's coding standards and best practices.

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
good @haseebzaki-07 

please also add for coolie booking 
check figma design 

schemas 
- time 
- location (pickup)
- location(depaurture)
-price 
- station

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
please do changes

**Comment by haseebzaki-07** [comment]
Sure I will add the changes

**Comment by dhairyagothi** [comment]
@haseebzaki-07 please also share a SS

**Comment by haseebzaki-07** [comment]
Hey @dhairyagothi I have added the coolie bookings backend
Screenshot 2024-10-07 234030

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
