### PR TITLE
Added  Mini Calendar in Bookingpage

### LINKED ISSUE #189: Adding the calender option in Station Services
# ✨ Feature Request

### **Description of the Feature**

image

Here I want to add the mini calender so the users can choose the date and time from that calendar.

### **Problem Statement**
Adding calender option to  users so that they can  easily select dates and times via a graphical interface, improving the user experience for booking, scheduling, or other time-based interactions.

### **Proposed Solution**
Using a custom calendar component from scratc

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes: #189

## Description of Changes

Added a mini calendar option so that they can easily select the current date or even can change to custom date.

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

Screenshot 2024-10-12 031957

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@SrijaVuppala295 resolve conflicts

**Comment by SrijaVuppala295** [comment]
@dhairyagothi , Resolved !!

**Comment by dhairyagothi** [comment]
image

check css @SrijaVuppala295

**Comment by SrijaVuppala295** [comment]
image

## @dhairyagothi  , Its running correctly in my system , I have again checked and changed the code , once review it.

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
