### PR TITLE
Password-Recovery-Feature

### LINKED ISSUE #375: Integrate Password Recovery Feature
# ✨ Feature Request: Integrate Password Recovery Feature

### **Description of the Feature**

This feature will enable users to recover their passwords using OTP-based authentication through a responsive UI. Initially, the process will be simulated with alerts to demonstrate the flow, with the option to integrate actual OTP APIs later for enhanced security.

### **Problem Statement**

Currently, users who forget their passwords cannot recover their accounts. This feature solves the issue by providing a simple, intuitive way to reset passwords, improving the overall user experience.

### **Proposed Solution**

Add a Password Recovery Page with input fields for email/username and OTP.
Simulate OTP functionality using alerts for easy demonstration.
Provide feedback on success or failure to the user through UI messages.
Optional: Add support for backend integration in future for actual OTP verification.

### **Alternatives Considered**

Integrating third-party password recovery services.

### **Additional Context**

This feature enhances the usability of the application, especially for users who frequently reset passwords. 

### **Are you participating in GSSoC?**
- [x ] Yes
- [ ] No

Screenshot 2024-10-15 192639
Screenshot 2024-10-20 025545
Screenshot 2024-10-15 022439
Screenshot 2024-10-15 024732

### PR DESCRIPTION
**Pull request by saras-69**
# Pull Request Template for GSoC 2024

## Related Issue:  #375 Integrate Password Recovery Feature

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes: #375

## Description of Changes

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

This PR introduces the Password Recovery Feature, allowing users to recover their forgotten passwords through a secure email verification process.

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [X] Performance Improvement
- [ ] Documentation Update
- [] Code Refactoring
- [X] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

Screenshot 2024-10-22 231431

https://github.com/user-attachments/assets/4835f5c8-7d22-472a-87ef-14d464ce64a3

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

This feature ensures a seamless and secure password recovery process for users and contributes to a better user experience.

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by saras-69** [comment]
Hey @dhairyagothi, I have submitted a pull request for the Password Recovery Feature, which enhances the app's usability and security by enabling users to securely reset forgotten passwords. The implementation required significant effort, including backend validation and front-end updates. I believe this aligns with the criteria for a Level 3 task, and I kindly request that this tag be assigned to the PR.

**Comment by dhairyagothi** [comment]
@saras-69 please sync fork there is a recent PR merged

**Comment by saras-69** [comment]
> @saras-69 please sync fork there is a recent PR merged

@dhairyagothi done

**Comment by saras-69** [comment]
> Hey @dhairyagothi, I have submitted a pull request for the Password Recovery Feature, which enhances the app's usability and security by enabling users to securely reset forgotten passwords. The implementation required significant effort, including backend validation and front-end updates. I believe this aligns with the criteria for a Level 3 task, and I kindly request that this tag be assigned to the PR.

Could you please take a moment to review it? Your feedback and consideration for the Level 3 tag would be greatly appreciated.

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
