### PR TITLE
Hamburger menu

### LINKED ISSUE #396: Issue in Hamburger Menu
# 🖥️ Frontend Issue

### **Description**
The hamburger menu isn't actually the hamburger menu, it is the navbar which is working like the hamburger menu.
I can enhance the hamburger menu.

Please assign this issue to me :)

### **Screenshots or Video**
Commenting out hamburger menu doesn't affect anything:

image
image

But commenting out Navbar will affect this:

image
image

### Are you participating in GSSoC?
- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by TanmayKalra09**
# Pull Request Template for GSoC 2024

## Related Issue

None

closes: https://github.com/dhairyagothi/StationGuide/issues/396

## Description of Changes

Previously Navbar was working like ham burger menu, I have implemented proper Hamburger menu and also enhanced it.

## Type of Pull Request

- [X] Bug Fix
- [X] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
image

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ ] I have added comments to my code where necessary for clarity.
- [ ] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
previous one is good keep it as figma design please @TanmayKalra09

**Comment by dhairyagothi** [comment]
also increase some width

**Comment by TanmayKalra09** [comment]
Hey @dhairyagothi, I have changed the hamburger menu which is inspired by Figma design. Secondly, I have increased the width of the hamburger menu from 250px to 350px

image

**Comment by dhairyagothi** [comment]
conflicts @TanmayKalra09

**Comment by dhairyagothi** [comment]
image

check this navbar 
also change width to `w-1/4`

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
please use tailwind css its hard to handle a lot files of css as well as jsx

**Comment by TanmayKalra09** [comment]
@dhairyagothi done with the changes. 
Menu width is now 25%, and tailwind is used.

**Comment by dhairyagothi** [comment]
image

fix this also search icon is not there

**Comment by TanmayKalra09** [comment]
@dhairyagothi Please review the changes.
image

**Pull request closed without merging**
