### PR TITLE
stationcode

### PR DESCRIPTION
**Pull request by the-matrixneo**
HI @dhairyagothi sir !!!! This pull request resolves the issue listed in issue #223 

I have added station code with station name and have also added some stations to allow better and simple use of website.
**Please** check the changes made in file and **Upgrade the level of issue** if possible. Its my humble request you to commit it to the main branch if you find changes satisfactory. 

 

## Description of Changes

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

## Type of Pull Request

- [ ] Bug Fix
- [ ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [X ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [ X] I have reviewed my code before submission.
- [X ] I have read and followed the project's Contribution Guidelines.
- [X ] I have tested the code thoroughly.
- [ ] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X ] I have added comments to my code where necessary for clarity.
- [ X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X ] My PR addresses only one issue; I have created separate PRs for other issues.
- [X ] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.
 Thanks you,
Dakshata
(GSSoC'24 Contributor , hactoberfest , )
## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@daky2024 conflicts

**Review by dhairyagothi — APPROVED** [review]

**Comment by the-matrixneo** [comment]
I'll be rechecking .

**Comment by dhairyagothi** [comment]
[11:22:21.509] Running build in Washington, D.C., USA (East) – iad1
[11:22:21.620] Cloning github.com/dhairyagothi/StationGuide (Branch: station/stationcode, Commit: 54bb3f1)
[11:22:23.138] Cloning completed: 1.515s
[11:22:24.169] Restored build cache from previous deployment (7r7nNw9wT5oGKT2mGDJgVKCkCxHA)
[11:22:24.286] Running "vercel build"
[11:22:25.949] Vercel CLI 37.8.0
[11:22:27.494] Installing dependencies...
[11:22:28.879] 
[11:22:28.880] up to date in 1s
[11:22:28.880] 
[11:22:28.881] 165 packages are looking for funding
[11:22:28.881]   run `npm fund` for details
[11:22:28.897] Running "npm run build"
[11:22:29.033] 
[11:22:29.034] > station-saarthi@0.0.0 build
[11:22:29.034] > vite build
[11:22:29.034] 
[11:22:29.285] [36mvite v5.4.8 [32mbuilding for production...[36m[39m
[11:22:29.616] transforming...
[11:22:31.046] [32m✓[39m 11 modules transformed.
[11:22:31.049] [31mx[39m Build failed in 1.73s
[11:22:31.050] [31merror during build:
[11:22:31.050] [31m[vite:esbuild] Transform failed with 1 error:
[11:22:31.051] /vercel/path0/frontend/src/Pages/stations.jsx:170:8: ERROR: The symbol "stations" has already been declared[31m
[11:22:31.051] file: [36m/vercel/path0/frontend/src/Pages/stations.jsx:170:8[31m
[11:22:31.051] [33m
[11:22:31.051] [33mThe symbol "stations" has already been declared[33m
[11:22:31.051] 168|    ];
[11:22:31.051] 169|  
[11:22:31.051] 170|    const [stations, setStations] = useState(allStations);
[11:22:31.051]    |          ^
[11:22:31.051] 171|  
[11:22:31.057] 172|  
[11:22:31.058] [31m
[11:22:31.058]     at failureErrorWithLog (/vercel/path0/frontend/node_modules/esbuild/lib/main.js:1472:15)
[11:22:31.058]     at /vercel/path0/frontend/node_modules/esbuild/lib/main.js:755:50
[11:22:31.058]     at responseCallbacks.<computed> (/vercel/path0/frontend/node_modules/esbuild/lib/main.js:622:9)
[11:22:31.058]     at handleIncomingPacket (/vercel/path0/frontend/node_modules/esbuild/lib/main.js:677:12)
[11:22:31.058]     at Socket.readFromStdout (/vercel/path0/frontend/node_modules/esbuild/lib/main.js:600:7)
[11:22:31.058]     at Socket.emit (node:events:519:28)
[11:22:31.058]     at addChunk (node:internal/streams/readable:559:12)
[11:22:31.058]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[11:22:31.059]     at Readable.push (node:internal/streams/readable:390:5)
[11:22:31.061]     at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)[39m
[11:22:31.103] Error: Command "npm run build" exited with 1
[11:22:31.301] 



check this deployment error on vercel

**Comment by dhairyagothi** [comment]
image

**Comment by the-matrixneo** [comment]
Screenshot_15-10-2024_114617_vercel com
is this in index.html file

**Comment by the-matrixneo** [comment]
@dhairyagothi sir is the issue resolved? Is my PR ready to merge?

**Review by dhairyagothi — APPROVED** [review]

**Comment by dhairyagothi** [comment]
closes: #223

**Pull request merged**
