### PR TITLE
In this Pr i made all the routes necessary from the landing page , and add some code in the new pages that were empty for initial period , and i made half of the buttons go to their respective routes

### PR DESCRIPTION
**Pull request by Raja-Abrar-Khan**
## Description of Changes

In this Pr i made all the routes necessary from the landing page , and add some code in the new pages that were empty for initial period , and i added some codes in the new pages and make half of the buttons navigate to their respective pages.
in my next pr i will make the other remaining buttons go to their respective button and in half of the buttons , now if you click in the image it will navigate to the respective route . In My next pr i will make the other buttons to work like this too. Will make steady changes and make this project better.

## Type of Pull Request

- [x] Bug Fix
- [x] New Feature
- [x] Performance Improvement
- [ ] Documentation Update
- [x] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
In the ss you can see the new routes in next pr i will make all the buttons left to navigate to the their respective route
Screenshot 2024-10-09 013633
Screenshot 2024-10-09 013642
Screenshot 2024-10-09 013658
Screenshot 2024-10-09 013707
Screenshot 2024-10-09 013721
Screenshot 2024-10-09 013731
Screenshot 2024-10-09 013806

## Checklist for Contributor

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [ ] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  Merge this PR i will then start working on the things i told in the description and thank you for merging My earlier PR.

**Comment by dhairyagothi** [comment]
What is issue no , ?@Raja-Abrar-Khan

**Comment by Raja-Abrar-Khan** [comment]
ohh, sorry I forgot to make this an Issue , let me make and give you issue number

**Comment by Raja-Abrar-Khan** [comment]
@dhairyagothi  ,#152 issue number for this one. Now merge this PR from next time i will make every issue and add issue number

**Comment by dhairyagothi** [comment]
@Raja-Abrar-Khan dont make PR before issue is not assigned to you . there is already same issue

**Comment by Raja-Abrar-Khan** [comment]
I made routes in app.jsx as well i added code in the new components also . and that issue is 3 days older it doesn't take that long .
And that issue is only adding route to the buttons that i as going to do in next pr i won't do it then if thats the case now please merge this pr the thing i am doing in this pr and that 3 days old issue are not exactly same

**Pull request merged**
