### PR TITLE
Offline First Experience with Caching and Sync Status Indicator

### LINKED ISSUE #463: Offline First Experience with Caching and Sync Status Indicator
### Offline First Experience with Caching and Sync Status Indicator

In today’s digital environment, users often encounter connectivity issues, which can disrupt their interaction with a website or application. Implementing an "Offline First" approach could greatly improve user experience, especially for those accessing the platform in areas with intermittent internet access. 

The idea is to integrate offline support in the app, ensuring users can still browse core content and access cached data even when they temporarily lose connectivity. By using service workers to cache essential assets and certain frequently accessed data, we can ensure that the application remains accessible and performs smoothly offline. Additionally, we’ll implement a **Sync Status Indicator** to keep users informed about their connectivity state. This status component can display whether they’re online, offline, or in a syncing state, helping them better understand the app's behavior. 

For example, consider a platform similar to YouTube. Offline capabilities would allow users to load recent data or static content even if their connection is unstable, making for a seamless experience. The sync status indicator adds transparency, showing users when their content is being updated or when the app is operating with cached data.

This enhancement would add significant reliability to the application, benefiting a wide range of users, and setting the project apart from others that don’t offer offline functionality.

@dhairyagothi  Assign this to me under GSSoC 2024 Ext and Hacktoberfest. I will work on this issue.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Pull Request Template for GSoC 2024

## Related Issue 

closes: #463 

### Offline First Experience with Caching and Sync Status Indicator

In today’s digital environment, users often encounter connectivity issues, which can disrupt their interaction with a website or application. Implementing an "Offline First" approach could greatly improve user experience, especially for those accessing the platform in areas with intermittent internet access. 

The idea is to integrate offline support in the app, ensuring users can still browse core content and access cached data even when they temporarily lose connectivity. By using service workers to cache essential assets and certain frequently accessed data, we can ensure that the application remains accessible and performs smoothly offline. Additionally, we’ll implement a **Sync Status Indicator** to keep users informed about their connectivity state. This status component can display whether they’re online, offline, or in a syncing state, helping them better understand the app's behavior. 

For example, consider a platform similar to YouTube. Offline capabilities would allow users to load recent data or static content even if their connection is unstable, making for a seamless experience. The sync status indicator adds transparency, showing users when their content is being updated or when the app is operating with cached data.

This enhancement would add significant reliability to the application, benefiting a wide range of users, and setting the project apart from others that don’t offer offline functionality.

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [X] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

## Screenshots / Demo (if applicable)

https://github.com/user-attachments/assets/c39d2e93-43e9-4639-a853-2c65ecb620f8

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

@dhairyagothi Please check this PR and merge this and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. I  think this should be a level 3 PR because this feature is completly new and very much needed for a professional website as people might think that the site is not working when their own internet connection is not working so i have implemented that. 

If you have any doubts and issues regarding this you can put them here.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
And it is working in all the pages so + point for that,

**Comment by dhairyagothi** [comment]
@tarunkumar2005 please sync fork in video i can see you haven't sync fork from a long time

**Comment by tarunkumar2005** [comment]
@dhairyagothi Done

**Comment by tarunkumar2005** [comment]
i have already sync fork just i was 15 commits behind right now did those also

**Review by dhairyagothi — APPROVED** [review]

**Comment by dhairyagothi** [comment]
ok good @tarunkumar2005

**Pull request merged**
