### PR TITLE
enhanced searchBar's appearance 

### PR DESCRIPTION
**Pull request by iamsaura8h**
# Pull Request Template for GSoC 2024

## Related Issue
None

## Description of Changes

Removed the unnecessary border line from the search bar when expanded and reduced the padding from 8px to 4px, resulting in a cleaner, more refined appearance. These adjustments make the search bar look sleeker and more stylish. Please refer to the screenshots below for a visual comparison.

## Type of Pull Request

- [ ] Bug Fix
- [ ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [x] Other (Specify): improved UI/UX

### before 
is10

### after 
is10sol

## Checklist for Contributor

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information
There's no alteration to any other except the code which needed to be changed (2 Lines here).
Thank you for letting me work on this issue

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@iamsaura8h how can  i assign you level 1 with just one line code chage 

please make some more changes make search bar animated

**Comment by iamsaura8h** [comment]
@dhairyagothi okay got it , i will make more stylish and animated

**Comment by iamsaura8h** [comment]
hey @dhairyagothi ,
i have made some new commits to this PR which makes the search bar look better and more user-friendly. I **added some nice animations**  that make it expand and collapse smoothly and **modern colors** which go with the theme of Station Saarthi app, which gives it a more modern feel.
Also, The **search and clear icons change color** when you hover over them, making it clear that they are interactive.

here's the preview

https://github.com/user-attachments/assets/a0d61e67-98e9-43b3-aedd-f087a4332105

Hope this changes are worth Level1 tags , also do provide `gssoc-ext` and `hacktoberfest-accepted` tags for this PR 😊
Thank you

**Comment by dhairyagothi** [comment]
update fork 

image

nabvbar is changed totally

**Comment by iamsaura8h** [comment]
@dhairyagothi fork updated , sorry for the hassle its my first time doing all these but i am learning.
Hope i am doing it right.
Thank you

**Comment by dhairyagothi** [comment]
> @dhairyagothi fork updated , sorry for the hassle its my first time doing all these but i am learning.
> Hope i am doing it right.
> Thank you

@iamsaura8h i will check it soon currently not using laptop will check and update till night

**Comment by dhairyagothi** [comment]
bro again same problem hamburger is removed in your PR

image

see

**Comment by iamsaura8h** [comment]
you have already fixed the searchBar with some other's PR so i am closing this PR

**Pull request closed without merging**
