### PR TITLE
Changed the Icons according to the suitable format on the frontend

### PR DESCRIPTION
**Pull request by rebornstar1**
# Pull Request Template for GSoC 2024

## Related Issue

#28 

## Description of Changes

This PR resolves the issue where the icons for services like Navigation, Booking, and Station were not displayed properly. The labels were visible, but the icons appeared misaligned or partially obscured due to CSS errors, improper scaling, and/or transparency issues. The following changes were made to correct the issue:
1. Adjusted the icon layout to ensure proper alignment.
2. Corrected Tailwind CSS properties affecting icon scaling.
3. Tested across different screen sizes to ensure responsiveness.

## Type of Pull Request

- [ X] Bug Fix
- [ ] New Feature
- [x] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

Upload
![Screenshot 2024-10-04 091645
ing Screenshot 2024-10-04 091625.png…]()

## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ ] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

### Contribution Levels

2. **Task Categories:**

- Medium

4. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
image

Check figma design StationGuideFigma.md

want like this

**Comment by rebornstar1** [comment]
Requested Changes are done, Please Let Me know if you are expecting something else
Screenshot 2024-10-04 161738
Screenshot 2024-10-04 161805

**Review by dhairyagothi — CHANGES_REQUESTED** [review]
image

well done bro @rebornstar1 
jus remove this two bookings

**Comment by rebornstar1** [comment]
Requested changes are done, please review it once.

**Comment by dhairyagothi** [comment]
Perfect bro 👍🏻 well done @rebornstar1

**Review by dhairyagothi — APPROVED** [review]

**Review by dhairyagothi — APPROVED** [review]

**Pull request merged**
