### PR TITLE
Add functionality to Schedule Page

### PR DESCRIPTION
**Pull request by manya1632**
# Pull Request Template for GSoC 2024 && Hacktoberfest 2024

## Related Issue
#433 
closes:

## Description of Changes

I have used an api to fetch the schedule of train if the train number is entered 
API used  : http://indianrailapi.com/api/v2/TrainSchedule/apikey/<apikey>/TrainNumber/<TrainNumber>/

one just needs to modify the code by adding their indian rail api key after login in to the website https://indianrailapi.com/api-collection/train-schedule

## Type of Pull Request

- [ ] Bug Fix
- [ ] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [X] Other (Specify): Backend Issue

## Screenshots / Demo (if applicable)
Screenshot 2024-10-26 164448

[](url)
## Checklist for Contributor
use'X' in [ ] to check it .

- [X] I have reviewed my code before submission.
- [X] I have read and followed the project's Contribution Guidelines.
- [X] I have tested the code thoroughly.
- [X] I have attached related issue numbers, screenshots, or videos (if applicable).
- [X] I have added comments to my code where necessary for clarity.
- [X] I have checked the existing code base and my changes do not introduce any breaking changes.
- [X] My PR addresses only one issue; I have created separate PRs for other issues.
- [X] I have ensured that the PR does not include unrelated files.
- [X] I am mindful of the project's coding standards and best practices.

## Additional Information

The user needs to enter their API key after login in Indian Rail api websitye
## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by manya1632** [comment]
Please look and resolve this 
Screenshot 2024-10-26 220140

**Comment by dhairyagothi** [comment]
> Please look and resolve this Screenshot 2024-10-26 220140

this will be done after PR merge

**Review by dhairyagothi — APPROVED** [review]

**Comment by dhairyagothi** [comment]
@manya1632 can you please tell how to get api key ??

**Comment by dhairyagothi** [comment]
closes : #433

**Comment by manya1632** [comment]
Yes sure ! 
To get the API key , first go to this website https://indianrailapi.com/api-collection and sign up yourself , enter details and then  you go the verification part, where you need to enter the email and the verification code sent to that email you entered at the first place, then again you need to login yourself with the username and password sent to your email. Here you're logged in . At your left hand side you can see the API key section which contains your api .

**Pull request merged**
