### PR TITLE
Add Privacy and Policy page with styling

### LINKED ISSUE #362: Privacy & Policy Page
# ✨ Feature Request

### **Description of the Feature**
We can implement a Proper privacy & policy page on the website's footer.

### **Are you participating in GSSoC?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by TanmayKalra09**
# Pull Request Template for GSoC 2024

## Related Issue

None

closes: https://github.com/dhairyagothi/StationGuide/issues/362

## Description of Changes

Added Privacy and Policy page with styling. The link for Privacy & policy is located on Footer

## Type of Pull Request

- [ ] Bug Fix
- [X] New Feature
- [ ] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

image
image
image

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [ ] I have added comments to my code where necessary for clarity.
- [ ] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@TanmayKalra09 its looking too big make it small

**Comment by dhairyagothi** [comment]
make font and padding short

**Comment by TanmayKalra09** [comment]
@dhairyagothi done with the changes, please review it once.

**Comment by dhairyagothi** [comment]
do one thing remove it from footer and add it in hamburger menu

**Comment by TanmayKalra09** [comment]
@dhairyagothi done with the changes.

**Comment by dhairyagothi** [comment]
please resolve conflicts @TanmayKalra09

**Comment by TanmayKalra09** [comment]
@dhairyagothi I have resolved the conflicts, please review it once.

**Comment by dhairyagothi** [comment]
great @TanmayKalra09

**Pull request merged**
