### PR TITLE
postion the language/button

### PR DESCRIPTION
**Pull request by Sandigupta**
# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes:

## Description of Changes

[Provide a concise description of the changes introduced by this PR, detailing what’s been added, modified, or fixed.]

## Type of Pull Request

- [x] Bug Fix
- [ ] New Feature
- [x] Performance Improvement
- [ ] Documentation Update
- [ ] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)
Screenshot 2024-10-17 194230

[Include any screenshots, GIFs, or videos that demonstrate the change or feature, if available.]

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

### CODE REVIEW

**Comment by Sandigupta** [comment]
@dhairyagothi Please merge this PR.
Thanks

**Comment by dhairyagothi** [comment]
you have removed search icon in PR

**Comment by Sandigupta** [comment]
after my change.........................................................................................................................
screencapture-localhost-5173-2024-10-17-23_34_30

Screenshot 2024-10-17 233308

before my change......................................................................................................................................
screencapture-stationguide-onrender-2024-10-17-23_31_45

**Comment by Sandigupta** [comment]
@dhairyagothi Please merge this PR.
thanks

**Comment by Sandigupta** [comment]
@dhairyagothi, you assigned that it was a level 2 issue earlier.

**Comment by Sandigupta** [comment]
@dhairyagothi 
Apart from that, I appreciate you allowing me to submit a PR for your project.

**Pull request merged**
